### PR TITLE
Added spanish JSON file

### PR DESCRIPTION
**Pull request by guillermohs9**
Talked to Logan, followed what was done on the German Translation and this is the pull request to include Spanish file

### CODE REVIEW

**Comment by TRoskop** [comment]
Hi @guillermohs9 ,
to add the spanish language, you also have to add your language here:
https://github.com/TRoskop/hextris/blob/gh-pages/js/languages/language-server.js#L17

Oh, and you should name it "es_es" :D

**Comment by guillermohs9** [comment]
I did the changes, we're working on a school project with a couple of mates
and we're extremely new to github! Is it ok?
Cheers!

2015-10-27 18:52 GMT-03:00 Thomas Roskop <notifications@github.com>:

**Comment by TRoskop** [comment]
I'll check it later - but still today.

**Comment by TRoskop** [comment]
So, I checked your files and added them. 
But as they had some smaller misstakes and because I also changed the script a little bit I have not "accepted" request but I copied the files out and added them by hand.

Well done, thanks!

**Comment by guillermohs9** [comment]
So, hextris is in spanish now? Sorry, our git  skills are almost none
Thanks!

**Pull request closed without merging**
